# Generated by Django 6.0b1 on 2025-12-27 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DSAPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DSATopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DSAPatternQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_heading', models.CharField(max_length=1000)),
                ('question_URL', models.URLField(blank=True, null=True)),
                ('solved', models.BooleanField(default=False)),
                ('solved_date', models.DateTimeField(blank=True, null=True)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboard.dsapattern')),
            ],
        ),
        migrations.AddField(
            model_name='dsapattern',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboard.dsatopics'),
        ),
    ]
